# Generated by Django 3.2.15 on 2022-09-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220901_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#33B918', 'Зеленый'), ('#f6fa05', 'Желтый'), ('#052efa', 'Синий'), ('#0BDA51', 'Малахит'), ('#FCDD76', 'Песок'), ('#0047AB', 'Кобальт'), ('#DDA0DD', 'Орхидея')], max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
